### ISSUE TITLE
How to write and run a new instruction properly?

### ISSUE THREAD

**Issue by agn-7** [handrew/browserpilot#7]
I'm trying to write a new instruction as an objective or goal to be run. However, it doesn't go quite well and stuck in middle of way.

Here's the instruction I've written so far:

```yaml
instructions:
- BEGIN_FUNCTION open_github_issue
- Go to Google.com
- Find all textareas.
- Find the first visible textarea.
- Click on the first visible textarea.
- Type in "netbox github" and press enter.
- Wait 2 seconds.
- Find all anchor elements that link to GitHub.
- Click on the first one.
- Wait 2 seconds.
- Find all things related to the issues tab.
- Click on it.
- Wait 2 seconds.
- Filter for closed issues
- END_FUNCTION
- RUN_FUNCTION open_github_issue
- Wait for 10 seconds.
```

It progresses until the Netbox repository on Github, but it cannot click on the <kbd>Issues</kbd> Tab and further path . . .

I read somewhere in the readme, that this repo has been inspired by `natbot` project. Natbot can do this objective just with a plain objective prompt that such an instruction sequences. Is there any specific reason to do that?

**Comment by handrew** [comment]
Hey! It's really cool that you're using BrowserPilot! As you've noticed, it's a bit of an art to prompt it correctly, and sometimes it doesn't progress further. When I was using BrowserPilot more last year, a common debugging process that I found helpful was to inspect the code that was generated by the underlying LLM. If it's not clicking on the Issues tab, I suspect it has something to do with your instruction `"Find all things related to the issues tab"`, which is a bit vague. I would suggest instead "Click on the anchor element with id 'issues-tab'.", since this more precisely isolates the element you want to click.

On `natbot`: I was—and continue to be—inspired by Nat Friedman's project. In fact, I tried another attempt at coming up with an agent (which you can find in the [AgenticGPT repository](https://github.com/handrew/agentic_gpt/tree/main/agentic_gpt/registry)) to follow more general natural language prompts. I also have an uncommitted file for this repository on my local machine which attempts to extend `gpt_selenium_agent.py` to take more natural directions. However, I stopped development on this for two reasons:

1. GPT-3.5 at the time, and GPT-4, were still too indeterministic and unstable to reliably produce good results. Part of this is also inherent to the ambiguity of human language and communication as well. Accordingly, part of the design principles of BrowserPilot was in fact to prompt the user to be more precise in giving their instructions.
2. Multi-modal vision language models were on the horizon, and I figured that it made sense to just wait until those were more widely available. These days, it could be possible to rebuild BrowserPilot or natbot using a pixel-reading LLM, instead of one that parses the DOM.
